development:
  adapter: postgresql
  database: tijuana_dev
  username: postgres
  password: comida
  host: localhost

test:
  adapter: postgresql
  database: tijuana_test
  username: postgres 
  password: comida
  host: localhost

production:
  adapter: postgresql
  database: tijuana_pro
  username: postgres
  password: comida
  host: localhost
